# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "will_paginate_couchrest"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["samlown"]
  s.date = "2013-04-05"
  s.description = "generate views specifically with support for using will_paginate with them"
  s.email = "me@samlown.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/will_paginate_couchrest.rb",
    "lib/will_paginate_couchrest/class_methods.rb",
    "lib/will_paginate_couchrest/proxy_methods.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/will_paginate_couchrest_spec.rb",
    "will_paginate_couchrest.gemspec"
  ]
  s.homepage = "http://github.com/samlown/will_paginate_couchrest"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "adds will-paginate support to CouchRest"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<couchrest>, [">= 0.35"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<couchrest>, [">= 0.35"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<couchrest>, [">= 0.35"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

